# Generated by Django 5.1.6 on 2025-08-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('aadhaar', models.CharField(blank=True, max_length=12)),
                ('vaccine_name', models.CharField(max_length=50)),
                ('dose', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CenterHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='healthcenters',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='center_name',
        ),
        migrations.AddField(
            model_name='healthcenters',
            name='district',
            field=models.CharField(default='Unknown District', max_length=100),
        ),
        migrations.AddField(
            model_name='healthcenters',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='center_profiles/'),
        ),
        migrations.AddField(
            model_name='healthcenters',
            name='thaluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='home.healthcenters'),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='doses',
            field=models.CharField(default='Single Dose', max_length=255),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='vaccine_category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='healthcenters',
            name='center_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='healthcenters',
            name='center_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcenters',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcenters',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='healthcenters',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcenters',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.healthcenters'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userreg'),
        ),
        migrations.AddField(
            model_name='centerholiday',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.healthcenters'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userreg'),
        ),
        migrations.AddField(
            model_name='notification',
            name='health_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.healthcenters'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userreg'),
        ),
        migrations.DeleteModel(
            name='VaccineSlots',
        ),
    ]
